version: "3"
services:
  db:
    image: postgres:14.1
    ports:
      - "5433:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    command: postgres -c stats_temp_directory=/tmp
  api:
    build: .
    tty: true
    stdin_open: true
    ports:
      - "4000:3000"
    volumes:
      - ".:/wataridori"
      - bundle:/usr/local/bundle
      - rails_cache:/wataridori/tmp/cache
    depends_on:
      - db
    command: bash -c "bundle install && rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
volumes:
  bundle:
    driver: local
  db_data:
    driver: local
  rails_cache:
