mysql: &mysql
  adapter: mysql2
  encoding: utf8mb4
  host: db
  username: root
  password: 123456
  pool: 5
postgres: &postgres
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *mysql
  database: wataridori_development
test:
  <<: *mysql
  host: 127.0.0.1
  database: wataridori_test
production:
  <<: *postgres
  database: wataridori_production
  username: wataridori
  password: <%= ENV['WATARIDORI_PASSWORD'] %>
