default: &default
  adapter: mysql2
  encoding: utf8mb4
  host: db
  username: root
  password: root
  pool: 5

development:
  <<: *default
  database: wataridori_development

test:
  <<: *default
  database: wataridori_test

production:
  <<: *default
  host: localhost
  database: wataridori_production
  username: wataridori
  password: <%= ENV['WATARIDORI_PASSWORD'] %>
