Skill.create!([
  {name: "Vietnamese", percent: 100, skill_type: "language"},
  {name: "Japanese", percent: 40, skill_type: "language"},
  {name: "English", percent: 55, skill_type: "language"},
  {name: "Ruby", percent: 70, skill_type: "technology"},
  {name: "Javascript", percent: 58, skill_type: "technology"},
  {name: "VueJS", percent: 55, skill_type: "technology"},
  {name: "ReactJS", percent: 40, skill_type: "technology"},
  {name: "MySQL", percent: 65, skill_type: "technology"},
  {name: "UI/UX", percent: 68, skill_type: "technology"},
  {name: "Git", percent: 75, skill_type: "technology"},
  {name: "Docker", percent: 55, skill_type: "technology"},
])

Favorite.create!([
  {image: "https://res.cloudinary.com/phucdx/image/upload/v1623479619/wataridori/images/fujita-maiko_nz5lj0.jpg",
    name: "Maiko Fujita", favorite_type: "singer"},
  {image: "https://res.cloudinary.com/phucdx/image/upload/v1623422532/wataridori/images/noriko-sakai_nvsnzx.jpg",
    name: "Noriko Sakai", favorite_type: "singer"},
  {image: "https://res.cloudinary.com/phucdx/image/upload/v1602212641/wataridori/images/radwimps.jpg",
    name: "Radwimps", favorite_type: "singer"},
  {image: "https://res.cloudinary.com/phucdx/image/upload/v1623469822/wataridori/images/inori-minase_acuk9c.jpg",
    name: "Inori Minase", favorite_type: "singer"},
  {image: "https://res.cloudinary.com/phucdx/image/upload/v1623421641/wataridori/images/noriko-mitose_moy8ji.jpg",
    name: "Noriko Mitose", favorite_type: "singer"},
  {image: "https://res.cloudinary.com/phucdx/image/upload/v1602212641/wataridori/images/aoi-teshima.jpg",
    name: "Aoi Teshima", favorite_type: "singer"},
  {image: "https://res.cloudinary.com/phucdx/image/upload/v1623469284/wataridori/images/kenshi-yonezu_hlnjyy.jpg",
    name: "Kenshi Yonezu", favorite_type: "singer"},
  {image: "https://res.cloudinary.com/phucdx/image/upload/v1625385203/wataridori/images/ikimono-gakari_gczotc.jpg",
    name: "Ikimono Gakari", favorite_type: "singer"},
  {image: "https://res.cloudinary.com/phucdx/image/upload/v1623470806/wataridori/images/nagori-yuki_pmyodc.jpg",
    name: "なごり雪", favorite_type: "song"},
  {image: "https://res.cloudinary.com/phucdx/image/upload/v1623422929/wataridori/images/mizu-fuusen_f03o4l.jpg",
    name: "水風船", favorite_type: "song"},
  {image: "https://res.cloudinary.com/phucdx/image/upload/v1623423313/wataridori/images/lemon_tppomh.png",
    name: "レモン", favorite_type: "song"},
  {image: "https://res.cloudinary.com/phucdx/image/upload/v1623423455/wataridori/images/ookina-furudokei_j1j6ya.jpg",
    name: "大きな古時計", favorite_type: "song"},
  {image: "https://res.cloudinary.com/phucdx/image/upload/v1623423621/wataridori/images/uchiage-hanabi_w6ugst.jpg",
    name: "打上花火", favorite_type: "song"},
  {image: "https://res.cloudinary.com/phucdx/image/upload/v1623468350/wataridori/images/sakura_tfl9vc.jpg",
    name: "桜", favorite_type: "song"},
  {image: "https://res.cloudinary.com/phucdx/image/upload/v1623424126/wataridori/images/ato-hitotsu_ecutcq.jpg",
    name: "あとひとつ", favorite_type: "song"},
  {image: "https://res.cloudinary.com/phucdx/image/upload/v1623424209/wataridori/images/ne_c5r119.jpg",
    name: "ねぇ", favorite_type: "song"},
  {image: "https://res.cloudinary.com/phucdx/image/upload/v1625465895/wataridori/images/doraemon_jlmll0.png",
    name: "ドラえもん", favorite_type: "other"},
  {image: "https://res.cloudinary.com/phucdx/image/upload/v1625466887/wataridori/images/astronomy_v2yqyo.jpg",
    name: "Astronomy", favorite_type: "other"},
  {image: "https://res.cloudinary.com/phucdx/image/upload/v1625465893/wataridori/images/cydia_nogk9w.jpg",
    name: "iOS Jailbreaking", favorite_type: "other"},
  {image: "https://res.cloudinary.com/phucdx/image/upload/v1623481358/wataridori/images/novak_bsqmkl.jpg",
    name: "Novak Djokovic", favorite_type: "other"},
])

Song.create!([
  {name: "Kono Te De Dakitomerukara", author: "Kita Shuuhei",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623515030/wataridori/songs/KonoTeDeDakitomerukaraHiiroNoKake_3xs5u_azouwo.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623514968/wataridori/songs/cover/kono-te-de-dakitomerukara_eysojy.jpg"},
  {name: "Koi Ni Koishite", author: "Mai Kuraki",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623515143/wataridori/songs/KoiNiKoishite-MaiKuraki_45em3_myvgj8.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623515252/wataridori/songs/cover/koi-ni-koishite_wo0ioy.jpg"},
  {name: "Takanaru", author: "Fujita Maiko",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623515315/wataridori/songs/TakanaruHiiroNoKakeraSs2Opening-M_4c4xm_lpcpvl.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623515413/wataridori/songs/cover/takanaru_l0ssxl.jpg"},
  {name: "Muộn rồi mà sao còn", author: "Sơn Tùng M-TP",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623516441/wataridori/songs/muon-roi-ma-sao-con_omthlf.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623516295/wataridori/songs/cover/muon-roi-ma-sao-con_orrxm5.jpg"},
  {name: "Q&A Recital!", author: "Tomatsu Haruka",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623515615/wataridori/songs/QARecital-HarukaTomatsu_4bu2f_fgl5tf.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623515712/wataridori/songs/cover/QARecital_w2ztjr.jpg"},
  {name: "Tegami - Aisuru Anata E", author: "Fujita Maiko",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623515836/wataridori/songs/TegamiAisuruAnataE-MaikoFujita-2604512_cx6jzb.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623515917/wataridori/songs/cover/tegami_svtro9.jpg"},
  {name: "Ashita, Boku Wa Kimi Ni Ai Ni Iku", author: "Wakaba",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623515956/wataridori/songs/AshitaBokuwaKimiNiAiNiYuku-Wakab_35fqc_ntm5q4.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623516048/wataridori/songs/cover/AshitaBokuwaKimiNiAiNiYuku_yfgcpa.jpg"},
  {name: "Loser", author: "Kenshi Yonezu",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623516513/wataridori/songs/loser_n33kdr.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623516148/wataridori/songs/cover/loser_meussg.jpg"},
  {name: "Kanojo Wa Tabi Ni Deru", author: "Sana",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623553668/wataridori/songs/KanojoWaTabiNiDeru-Sana-5205413_qifbs8.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623553731/wataridori/songs/cover/KanojoWaTabiNiDeru_yltv3a.jpg"},
  {name: "Haiiro To Ao", author: "Kobasolo, Harutya",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623553838/wataridori/songs/HaiiroToAo-KobasoloHarutya-5458765_cl9dwc.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623553830/wataridori/songs/cover/haiiro-to-ao_m9hi31.jpg"},
  {name: "Harehare Ya", author: "Sou",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623553927/wataridori/songs/HarehareYa-Sou-5492450_uoe2nc.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623553921/wataridori/songs/cover/harehareya_xi7voh.jpg"},
  {name: "Nandemonaiya", author: "Mone Kamishiraishi",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623554045/wataridori/songs/NandemonaiyaMAXONERemix-MoneKamishiraishi-4774362_fonxbl.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623554036/wataridori/songs/cover/your-name_ug73xa.jpg"},
  {name: "Chiisana Koi No Uta", author: "Rie Takahashi",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623554157/wataridori/songs/ChiisanaKoiNoUta-RieTakahashi-5406701_hxshq6.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623554151/wataridori/songs/cover/chiisanakoi-no-uta_lcfltv.jpg"},
  {name: "Cảm ơn", author: "Đen ft. Biên",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623554778/wataridori/songs/cam-on_jhbwiq.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623554773/wataridori/songs/cover/cam-on_tevavr.jpg"},
  {name: "Lối nhỏ", author: "Đen ft. Phương Anh Đào",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623555040/wataridori/songs/loi-nho_pvg9v8.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623555021/wataridori/songs/cover/loi-nho_nc5jsk.jpg"},
  {name: "Ichinen Nikagetsu Hatsuka", author: "BRIGHT",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623554394/wataridori/songs/IchinenNikagetsuHatsuka-BRIGHT-2424747_deekzp.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623554388/wataridori/songs/cover/ichinen-nikagetsu-hatsuka_p7z8ei.jpg"},
  {name: "Ato Hitotsu", author: "Funky Monkey Babys",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623554263/wataridori/songs/AtoHitotsu-FunkyMonkeyBabys_344nf_r6iq7s.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623554257/wataridori/songs/cover/ato-hitotsu_yfebdy.jpg"},
  {name: "Hello Goodbye & Hello", author: "Anri Kumaki",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623556302/wataridori/songs/HelloGoodbyeHello-AnriKumaki_387ud_u4wemg.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623556293/wataridori/songs/cover/hello-goodbye-hello_xn8xn3.jpg"},
  {name: "Nee", author: "Fujita Maiko",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623561050/wataridori/songs/nee_x3vpcs.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623561043/wataridori/songs/cover/nee_uypqkr.jpg"},
  {name: "Anh đếch cần gì nhiều ngoài em", author: "Đen ft. Vũ., Thành Đồng",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623555351/wataridori/songs/anh-dech-can-gi-nhieu-ngoai-em_a1u0yo.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623555345/wataridori/songs/cover/anh-dech-can-gi-nhieu-ngoai-em_ejukwn.jpg"},
  {name: "Hotaru", author: "Fujita Maiko",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623556484/wataridori/songs/Hotaru-FujitaMaiko_3cmw5_ephzjf.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623556445/wataridori/songs/cover/hotaru_epphe6.jpg"},
  {name: "Mirai", author: "Garnidelia",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623560931/wataridori/songs/mirai_fziqwn.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623560920/wataridori/songs/cover/mirai_gqyun7.jpg"},
  {name: "Hirari", author: "Ohara Sakurako",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623561211/wataridori/songs/Hirari-OharaSakurako-4858306_mj1c1j.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623561205/wataridori/songs/cover/hirari_ln4cwg.jpg"},
  {name: "Kaze No Kyoku", author: "Anri Kumaki",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623561284/wataridori/songs/KazenoKioku-AnriKumaki_8bty_cuszy1.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623561281/wataridori/songs/cover/kaze-no-kyoku_iv7c2n.jpg"},
  {name: "Orange", author: "7!!",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623561403/wataridori/songs/orange_jfdntm.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623561394/wataridori/songs/cover/orange_kkcbes.jpg"},
  {name: "Trốn tìm", author: "Đen ft. MTV band",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623555201/wataridori/songs/tron-tim_bsqw42.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623555193/wataridori/songs/cover/tron-tim_iygak3.jpg"},
  {name: "Sakura (5cm/s)", author: "Ikimono Gakari",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623561544/wataridori/songs/Sakura5CmsOST-IkimonoGakari_4dvpj_tlcr8i.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623561526/wataridori/songs/cover/sakura_u1ggp2.jpg"},
  {name: "Centimeter", author: "7!!",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623561837/wataridori/songs/Centimeter-7-4153877_ubsoov.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623561829/wataridori/songs/cover/centimeter_bliol7.jpg"},
  {name: "Arigatou", author: "Kokia",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623561927/wataridori/songs/Arigato-Kokia_3ckt_r1k25y.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623561922/wataridori/songs/cover/arigatou_vi9dom.jpg"},
  {name: "Kimi Ni Uso", author: "Hatsune Miku",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623562108/wataridori/songs/KimiNiUso-HatsuneMiku_4f52u_ei82rf.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623562094/wataridori/songs/cover/kimi-ni-uso_njqkzb.jpg"},
  {name: "Hyaku Renka", author: "Satomi Takasugi",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623562378/wataridori/songs/HyakuRenka-SatomiTakasugi_ubtx_mauwz6.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623562371/wataridori/songs/cover/hyaku-renka_vrthom.jpg"},
  {name: "Uchiage Hanabi", author: "Daoko, Kenshi Yonezu",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623562479/wataridori/songs/UchiageHanabi-DaokoKenshiYonezu-5113681_nwvuhl.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623562473/wataridori/songs/cover/uchiage-hanabi_h7o372.jpg"},
  {name: "Hana No Atosaki", author: "MAO",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623562584/wataridori/songs/HanaNoAtosaki-MAO-2628279_vsvdaj.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623562581/wataridori/songs/cover/hana-no-atosaki_gyy48l.jpg"},
  {name: "Kanawanai Koi Demo", author: "KG, Yumi Shizukusa",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623562670/wataridori/songs/KanawanaiKoiDemo-KGYumiShizukusa-3855519_na0q69.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623562664/wataridori/songs/cover/kanawanai-koi-demo_mg8woy.jpg"},
  {name: "Ooki Na Furudokei", author: "Noriko Mitose",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623562788/wataridori/songs/OokiNaFurudokeiGrandfathersClock-_p67z_y1jcna.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623562783/wataridori/songs/cover/ookina-furudokei_caqjt5.jpg"},
  {name: "Authentic Symphony", author: "Choucho",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623562895/wataridori/songs/Authenticsymphony-Choucho_3eqxa_w0mwtg.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623562891/wataridori/songs/cover/symphony_urbwl0.jpg"},
  {name: "Nagori Yuki", author: "Ayaka Hirahara",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623563020/wataridori/songs/NagoriYuki-AyakaHirahara-3119237_vdjq3u.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623563015/wataridori/songs/cover/nagori-yuki_hrjpip.webp"},
  {name: "Sayonara No Natsu", author: "Aoi Teshima",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623563132/wataridori/songs/SayonaraNoNatsu-AoiTeshima-1286051_bpuogv.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623563119/wataridori/songs/cover/sayonara-no-natsu_e0txhx.jpg"},
  {name: "Hanabi", author: "Fujita Maiko",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623563201/wataridori/songs/Hanabi-FujitaMaiko-5107708_sepczo.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623563197/wataridori/songs/cover/hanabi_bo2gxk.jpg"},
  {name: "Lemon", author: "Kenshi Yonezu",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623563325/wataridori/songs/Lemon-KenshiYonezu-5411306_etimkg.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623563313/wataridori/songs/cover/lemon_cgpiwj.jpg"},
  {name: "Shinkai Shoujo", author: "Hatsune Miku",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623563387/wataridori/songs/ShinkaiShoujo-HatsuneMiku_4bcc7_ljywbo.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623563383/wataridori/songs/cover/shinkai-shojou_fryvkx.jpg"},
  {name: "Sakurairo Mau Koro", author: "Mika Nakashima",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623563556/wataridori/songs/SakurairoMauKoro-MikaNakashima-2217441_lcbxuu.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623563552/wataridori/songs/cover/sakurairo-mau-koro_xopwf7.jpg"},
  {name: "Umbrella", author: "Itou Kashitarou",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623571534/wataridori/songs/Umbrella-KashitaroIto-2576613_eza9my.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623571525/wataridori/songs/cover/umbrella_hmedqe.jpg"},
  {name: "Bye Bye", author: "7!!",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623571671/wataridori/songs/bye-bye_zaampx.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623571660/wataridori/songs/cover/bye-bye_joure1.jpg"},
  {name: "Yoru no uta", author: "Junko Iwao",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623571779/wataridori/songs/Yorunouta-IwaoJunko_33kw_ks58qs.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623571772/wataridori/songs/cover/yoru-no-uta_azl8kv.jpg"},
  {name: "Hirari Hirari", author: "Hatsune Miku",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623571867/wataridori/songs/HirariHirari-HatsuneMiku_3zkhm_malavr.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623571863/wataridori/songs/cover/hirari-hirari_cwpjub.jpg"},
  {name: "Bài Này Chill Phết", author: "Đen ft. MIN",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623571992/wataridori/songs/bai-nay-chill-phet_ufvpvy.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623571982/wataridori/songs/cover/bai-nay-chill-phet_pe2ip1.jpg"},
  {name: "Hai triệu năm", author: "Đen ft. Biên",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623572088/wataridori/songs/2-trieu-nam_lhwwuk.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623572081/wataridori/songs/cover/2-trieu-name_jdf8tc.jpg"},
  {name: "Mizu Fuusen", author: "Fujita Maiko",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623572162/wataridori/songs/MizuFuusen-FujitaMaiko_3adty_h0apbi.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623572159/wataridori/songs/cover/mizu-fuusen_dxiajn.jpg"},
  {name: "Wishing", author: "Minase Inori",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623572229/wataridori/songs/Wishing-MinaseInori-4563352_jxbwq4.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623572224/wataridori/songs/cover/wishing_tghsbh.jpg"},
  {name: "Sakura Anata Ni Deaete Yokatta", author: "RSP",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623572320/wataridori/songs/SakuraAnataNiDeaeteYokatta-RSP-698987_z3yb6i.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623572317/wataridori/songs/cover/sakura-anata-ni-deaete-yokatta_vrwyps.jpg"},
  {name: "Hibiki No Shirabe", author: "Tetomu",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623572455/wataridori/songs/Hibikinoshirabe-Tetomu_a3ms_mgryhm.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623572452/wataridori/songs/cover/HibikiNoShirabe_bpze4m.jpg"},
  {name: "Aoi Usagi", author: "Noriko Sakai",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623572579/wataridori/songs/AoiUsagiNgoiSaoMayManOST-NorikoSakai-79721_swkith.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623572575/wataridori/songs/cover/AoiUsagi_kzgdjl.jpg"},
  {name: "Love Is A Beautiful Pain", author: "Nightcore",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623573948/wataridori/songs/LoveIsABeautifulPainEndlessTears-Nightcore-3981524_vtqiza.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623573942/wataridori/songs/cover/love-is-a-beautiful-pain_frprtx.jpg"},
  {name: "Kiseki", author: "Rie Takahashi",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623573820/wataridori/songs/Kiseki-RieTakahashi-6038192_aelbjy.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623573811/wataridori/songs/cover/kiseki_gyzoqc.jpg"},
  {name: "Orion (Acoustic Arrange)", author: "MarieFD",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623574042/wataridori/songs/OrionAcousticArrange-MarieFD-5895479_xnj3hd.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623574038/wataridori/songs/cover/orion_vjbown.jpg"},
  {name: "Kimi Dattara", author: "Happy Birthday",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623574131/wataridori/songs/KimiDattara-HappyBirthday-3757129_vnqk55.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623574110/wataridori/songs/cover/kimi-dattara_tdvfen.jpg"},
  {name: "Hirari Hirari", author: "Hatsune Miku",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623574213/wataridori/songs/HazyMoon-HatsuneMiku-1689454_rabvzg.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623574210/wataridori/songs/cover/hazy-moon_jkx1wz.jpg"},
  {name: "Yuki No Hana", author: "Mika Nakashima",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623574364/wataridori/songs/yuki-no-hana_fgt04c.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623574352/wataridori/songs/cover/yuki-no-hana_nenl49.jpg"}
])
