Skill.create!([
  {name: "Vietnamese", percent: 100, skill_type: "language"},
  {name: "Japanese", percent: 40, skill_type: "language"},
  {name: "English", percent: 55, skill_type: "language"},
  {name: "Ruby", percent: 75, skill_type: "technology"},
  {name: "Javascript", percent: 64, skill_type: "technology"},
  {name: "VueJS", percent: 45, skill_type: "technology"},
  {name: "ReactJS", percent: 30, skill_type: "technology"},
  {name: "MySQL", percent: 70, skill_type: "technology"},
  {name: "UI/UX", percent: 68, skill_type: "technology"},
  {name: "Git", percent: 85, skill_type: "technology"},
  {name: "Docker", percent: 65, skill_type: "technology"},
])

Favorite.create!([
  {image: "https://res.cloudinary.com/phucdx/image/upload/v1623479619/wataridori/images/fujita-maiko_nz5lj0.jpg",
    name: "藤田麻衣子", favorite_type: "singer"},
  {image: "https://res.cloudinary.com/phucdx/image/upload/v1623422532/wataridori/images/noriko-sakai_nvsnzx.jpg",
    name: "酒井法子", favorite_type: "singer"},
  {image: "https://res.cloudinary.com/phucdx/image/upload/v1602212641/wataridori/images/radwimps.jpg",
    name: "ラッドウインプス", favorite_type: "singer"},
  {image: "https://res.cloudinary.com/phucdx/image/upload/v1623469822/wataridori/images/inori-minase_acuk9c.jpg",
    name: "水瀬 いのり", favorite_type: "singer"},
  {image: "https://res.cloudinary.com/phucdx/image/upload/v1623421641/wataridori/images/noriko-mitose_moy8ji.jpg",
    name: "みとせのりこ", favorite_type: "singer"},
  {image: "https://res.cloudinary.com/phucdx/image/upload/v1602212641/wataridori/images/aoi-teshima.jpg",
    name: "手嶌葵", favorite_type: "singer"},
  {image: "https://res.cloudinary.com/phucdx/image/upload/v1623469284/wataridori/images/kenshi-yonezu_hlnjyy.jpg",
    name: "米津玄師", favorite_type: "singer"},
  {image: "https://res.cloudinary.com/phucdx/image/upload/v1625385203/wataridori/images/ikimono-gakari_gczotc.jpg",
    name: "いきものがかり", favorite_type: "singer"},
  {image: "https://res.cloudinary.com/phucdx/image/upload/v1623470806/wataridori/images/nagori-yuki_pmyodc.jpg",
    name: "なごり雪", favorite_type: "song"},
  {image: "https://res.cloudinary.com/phucdx/image/upload/v1623422929/wataridori/images/mizu-fuusen_f03o4l.jpg",
    name: "水風船", favorite_type: "song"},
  {image: "https://res.cloudinary.com/phucdx/image/upload/v1623423313/wataridori/images/lemon_tppomh.png",
    name: "レモン", favorite_type: "song"},
  {image: "https://res.cloudinary.com/phucdx/image/upload/v1625903535/wataridori/songs/cover/kaerinakunattayo_djm24m.jpg",
    name: "帰りたくなったよ", favorite_type: "song"},
  {image: "https://res.cloudinary.com/phucdx/image/upload/v1625902987/wataridori/songs/cover/kimigairu_cxtp8h.jpg",
    name: "キミがいる", favorite_type: "song"},
  {image: "https://res.cloudinary.com/phucdx/image/upload/v1625903234/wataridori/songs/cover/waratteitainda_dotayf.jpg",
    name: "笑ってたいんだ", favorite_type: "song"},
  {image: "https://res.cloudinary.com/phucdx/image/upload/v1623424126/wataridori/images/ato-hitotsu_ecutcq.jpg",
    name: "あとひとつ", favorite_type: "song"},
  {image: "https://res.cloudinary.com/phucdx/image/upload/v1625902782/wataridori/songs/cover/nakumonka_dtcwwa.jpg",
    name: "なくもんか", favorite_type: "song"},
  {image: "https://res.cloudinary.com/phucdx/image/upload/v1625465895/wataridori/images/doraemon_jlmll0.png",
    name: "ドラえもん", favorite_type: "other"},
  {image: "https://res.cloudinary.com/phucdx/image/upload/v1625466887/wataridori/images/astronomy_v2yqyo.jpg",
    name: "Astronomy", favorite_type: "other"},
  {image: "https://res.cloudinary.com/phucdx/image/upload/v1625465893/wataridori/images/cydia_nogk9w.jpg",
    name: "iOS Jailbreaking", favorite_type: "other"},
  {image: "https://res.cloudinary.com/phucdx/image/upload/v1623481358/wataridori/images/novak_bsqmkl.jpg",
    name: "Novak Djokovic", favorite_type: "other"},
])

Song.create!([
  {name: "なくもんか", author: "いきものがかり",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1625902548/wataridori/songs/nakumonka_jsfn9f.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1625902782/wataridori/songs/cover/nakumonka_dtcwwa.jpg"},
  {name: "ありがとう", author: "いきものがかり",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1625904346/wataridori/songs/arigatou_fkqnjw.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1625904338/wataridori/songs/cover/arigatou_qe4f3f.jpg"},
  {name: "この手で抱きとめるから", author: "喜多修平",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623515030/wataridori/songs/KonoTeDeDakitomerukaraHiiroNoKake_3xs5u_azouwo.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1626365897/wataridori/songs/cover/Kono-te-de-dakitomerukara_vc5pzu.jpg"},
  {name: "恋に恋して", author: "倉木麻衣",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623515143/wataridori/songs/KoiNiKoishite-MaiKuraki_45em3_myvgj8.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623515252/wataridori/songs/cover/koi-ni-koishite_wo0ioy.jpg"},
  {name: "高鳴る", author: "藤田麻衣子",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623515315/wataridori/songs/TakanaruHiiroNoKakeraSs2Opening-M_4c4xm_lpcpvl.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623515413/wataridori/songs/cover/takanaru_l0ssxl.jpg"},
  {name: "Muộn rồi mà sao còn", author: "Sơn Tùng M-TP",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1625927509/wataridori/songs/Muon_Roi_Ma_Sao_Con_-_Son_Tung_M-TP_pwtnbr.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623516295/wataridori/songs/cover/muon-roi-ma-sao-con_orrxm5.jpg"},
  {name: "手紙～愛するあなたへ", author: "藤田麻衣子",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623515836/wataridori/songs/TegamiAisuruAnataE-MaikoFujita-2604512_cx6jzb.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623515917/wataridori/songs/cover/tegami_svtro9.jpg"},
  {name: "東京盆踊り", author: "Namewee ft. 二宮芽生",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1625932908/wataridori/songs/tokyobon_udzoms.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1625932937/wataridori/songs/cover/tokyobon_vcageo.jpg"},
  {name: "明日、僕は君に会いに行く。", author: "Wakaba",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623515956/wataridori/songs/AshitaBokuwaKimiNiAiNiYuku-Wakab_35fqc_ntm5q4.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1626366028/wataridori/songs/cover/Ashita-boku_tskwfm.jpg"},
  {name: "Loser", author: "米津玄師",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623516513/wataridori/songs/loser_n33kdr.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623516148/wataridori/songs/cover/loser_meussg.jpg"},
  {name: "彼女は旅に出る", author: "鎖那",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623553668/wataridori/songs/KanojoWaTabiNiDeru-Sana-5205413_qifbs8.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623553731/wataridori/songs/cover/KanojoWaTabiNiDeru_yltv3a.jpg"},
  {name: "灰色と青", author: "米津玄師",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623553838/wataridori/songs/HaiiroToAo-KobasoloHarutya-5458765_cl9dwc.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623553830/wataridori/songs/cover/haiiro-to-ao_m9hi31.jpg"},
  {name: "ハレハレヤ", author: "Sou",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623553927/wataridori/songs/HarehareYa-Sou-5492450_uoe2nc.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623553921/wataridori/songs/cover/harehareya_xi7voh.jpg"},
  {name: "何でもないや", author: "上白石 萌音",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623554045/wataridori/songs/NandemonaiyaMAXONERemix-MoneKamishiraishi-4774362_fonxbl.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623554036/wataridori/songs/cover/your-name_ug73xa.jpg"},
  {name: "小さな恋のうた", author: "高橋李依",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623554157/wataridori/songs/ChiisanaKoiNoUta-RieTakahashi-5406701_hxshq6.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623554151/wataridori/songs/cover/chiisanakoi-no-uta_lcfltv.jpg"},
  {name: "Cảm ơn", author: "Đen ft. Biên",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623554778/wataridori/songs/cam-on_jhbwiq.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623554773/wataridori/songs/cover/cam-on_tevavr.jpg"},
  {name: "Lối nhỏ", author: "Đen ft. Phương Anh Đào",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623555040/wataridori/songs/loi-nho_pvg9v8.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623555021/wataridori/songs/cover/loi-nho_nc5jsk.jpg"},
  {name: "1年2ヶ月20日", author: "BRIGHT",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623554394/wataridori/songs/IchinenNikagetsuHatsuka-BRIGHT-2424747_deekzp.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623554388/wataridori/songs/cover/ichinen-nikagetsu-hatsuka_p7z8ei.jpg"},
  {name: "あとひとつ", author: "Funky Monkey Babys",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623554263/wataridori/songs/AtoHitotsu-FunkyMonkeyBabys_344nf_r6iq7s.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623554257/wataridori/songs/cover/ato-hitotsu_yfebdy.jpg"},
  {name: "ねぇ", author: "藤田麻衣子",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623561050/wataridori/songs/nee_x3vpcs.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1626366243/wataridori/songs/cover/nee_kjxy9f.jpg"},
  {name: "Anh đếch cần gì nhiều ngoài em", author: "Đen ft. Vũ., Thành Đồng",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623555351/wataridori/songs/anh-dech-can-gi-nhieu-ngoai-em_a1u0yo.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623555345/wataridori/songs/cover/anh-dech-can-gi-nhieu-ngoai-em_ejukwn.jpg"},
  {name: "蛍", author: "藤田麻衣子",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623556484/wataridori/songs/Hotaru-FujitaMaiko_3cmw5_ephzjf.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623556445/wataridori/songs/cover/hotaru_epphe6.jpg"},
  {name: "Mirai", author: "Garnidelia",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623560931/wataridori/songs/mirai_fziqwn.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623560920/wataridori/songs/cover/mirai_gqyun7.jpg"},
  {name: "ひらり", author: "大原櫻子",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623561211/wataridori/songs/Hirari-OharaSakurako-4858306_mj1c1j.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623561205/wataridori/songs/cover/hirari_ln4cwg.jpg"},
  {name: "風の記憶", author: "熊木杏里",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623561284/wataridori/songs/KazenoKioku-AnriKumaki_8bty_cuszy1.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623561281/wataridori/songs/cover/kaze-no-kyoku_iv7c2n.jpg"},
  {name: "オレンジ", author: "7!!",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623561403/wataridori/songs/orange_jfdntm.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623561394/wataridori/songs/cover/orange_kkcbes.jpg"},
  {name: "Trốn tìm", author: "Đen ft. MTV band",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623555201/wataridori/songs/tron-tim_bsqw42.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623555193/wataridori/songs/cover/tron-tim_iygak3.jpg"},
  {name: "Sakura", author: "いきものがかり",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623561544/wataridori/songs/Sakura5CmsOST-IkimonoGakari_4dvpj_tlcr8i.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623561526/wataridori/songs/cover/sakura_u1ggp2.jpg"},
  {name: "センチメートル", author: "7!!",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623561837/wataridori/songs/Centimeter-7-4153877_ubsoov.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1626366456/wataridori/songs/cover/centimeter_vkarrs.jpg"},
  {name: "ありがとう", author: "Kokia",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623561927/wataridori/songs/Arigato-Kokia_3ckt_r1k25y.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623561922/wataridori/songs/cover/arigatou_vi9dom.jpg"},
  {name: "君に嘘", author: "初音ミク",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623562108/wataridori/songs/KimiNiUso-HatsuneMiku_4f52u_ei82rf.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623562094/wataridori/songs/cover/kimi-ni-uso_njqkzb.jpg"},
  {name: "百恋歌", author: "高杉さと美",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623562378/wataridori/songs/HyakuRenka-SatomiTakasugi_ubtx_mauwz6.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623562371/wataridori/songs/cover/hyaku-renka_vrthom.jpg"},
  {name: "打上花火", author: "だをこ, 米津玄師",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623562479/wataridori/songs/UchiageHanabi-DaokoKenshiYonezu-5113681_nwvuhl.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623562473/wataridori/songs/cover/uchiage-hanabi_h7o372.jpg"},
  {name: "叶わない恋でも", author: "KG, 滴草由実",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623562670/wataridori/songs/KanawanaiKoiDemo-KGYumiShizukusa-3855519_na0q69.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623562664/wataridori/songs/cover/kanawanai-koi-demo_mg8woy.jpg"},
  {name: "大きな古時計", author: "みとせのりこ",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623562788/wataridori/songs/OokiNaFurudokeiGrandfathersClock-_p67z_y1jcna.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623562783/wataridori/songs/cover/ookina-furudokei_caqjt5.jpg"},
  {name: "Authentic Symphony", author: "ちょうちょ",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623562895/wataridori/songs/Authenticsymphony-Choucho_3eqxa_w0mwtg.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623562891/wataridori/songs/cover/symphony_urbwl0.jpg"},
  {name: "なごり雪", author: "平原綾香",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623563020/wataridori/songs/NagoriYuki-AyakaHirahara-3119237_vdjq3u.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623563015/wataridori/songs/cover/nagori-yuki_hrjpip.webp"},
  {name: "さよならの夏", author: "手嶌葵",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623563132/wataridori/songs/SayonaraNoNatsu-AoiTeshima-1286051_bpuogv.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623563119/wataridori/songs/cover/sayonara-no-natsu_e0txhx.jpg"},
  {name: "花火", author: "藤田麻衣子",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623563201/wataridori/songs/Hanabi-FujitaMaiko-5107708_sepczo.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623563197/wataridori/songs/cover/hanabi_bo2gxk.jpg"},
  {name: "Lemon", author: "米津玄師",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623563325/wataridori/songs/Lemon-KenshiYonezu-5411306_etimkg.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623563313/wataridori/songs/cover/lemon_cgpiwj.jpg"},
  {name: "深海少女", author: "初音ミク",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623563387/wataridori/songs/ShinkaiShoujo-HatsuneMiku_4bcc7_ljywbo.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623563383/wataridori/songs/cover/shinkai-shojou_fryvkx.jpg"},
  {name: "帰りたくなったよ", author: "いきものがかり",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1625903516/wataridori/songs/kaerinakunattayo_amyari.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1625903535/wataridori/songs/cover/kaerinakunattayo_djm24m.jpg"},
  {name: "風が吹いている", author: "いきものがかり",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1625904172/wataridori/songs/kazegafuteiru_kwq9mz.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1625904161/wataridori/songs/cover/kazegafuteiru_qwgge9.jpg"},
  {name: "桜色舞うころ", author: "中島美嘉",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623563556/wataridori/songs/SakurairoMauKoro-MikaNakashima-2217441_lcbxuu.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623563552/wataridori/songs/cover/sakurairo-mau-koro_xopwf7.jpg"},
  {name: "アンブレラ", author: "伊東歌詞太郎",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623571534/wataridori/songs/Umbrella-KashitaroIto-2576613_eza9my.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623571525/wataridori/songs/cover/umbrella_hmedqe.jpg"},
  {name: "バイバイ", author: "7!!",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623571671/wataridori/songs/bye-bye_zaampx.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623571660/wataridori/songs/cover/bye-bye_joure1.jpg"},
  {name: "夜の歌", author: "岩男潤子",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623571779/wataridori/songs/Yorunouta-IwaoJunko_33kw_ks58qs.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623571772/wataridori/songs/cover/yoru-no-uta_azl8kv.jpg"},
  {name: "ひらり、ひらり", author: "初音ミク",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623571867/wataridori/songs/HirariHirari-HatsuneMiku_3zkhm_malavr.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623571863/wataridori/songs/cover/hirari-hirari_cwpjub.jpg"},
  {name: "Bài Này Chill Phết", author: "Đen ft. MIN",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623571992/wataridori/songs/bai-nay-chill-phet_ufvpvy.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623571982/wataridori/songs/cover/bai-nay-chill-phet_pe2ip1.jpg"},
  {name: "Hai triệu năm", author: "Đen ft. Biên",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623572088/wataridori/songs/2-trieu-nam_lhwwuk.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623572081/wataridori/songs/cover/2-trieu-name_jdf8tc.jpg"},
  {name: "キミがいる", author: "いきものがかり",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1625902992/wataridori/songs/kimigairu_vyxsk3.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1625902987/wataridori/songs/cover/kimigairu_cxtp8h.jpg"},
  {name: "笑ってたいんだ", author: "いきものがかり",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1625903246/wataridori/songs/warattetainda_io2epo.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1625903234/wataridori/songs/cover/waratteitainda_dotayf.jpg"},
  {name: "水風船", author: "藤田麻衣子",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623572162/wataridori/songs/MizuFuusen-FujitaMaiko_3adty_h0apbi.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623572159/wataridori/songs/cover/mizu-fuusen_dxiajn.jpg"},
  {name: "Wishing", author: "水瀬いのり",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623572229/wataridori/songs/Wishing-MinaseInori-4563352_jxbwq4.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623572224/wataridori/songs/cover/wishing_tghsbh.jpg"},
  {name: "響の調べ", author: "岳美",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623572455/wataridori/songs/Hibikinoshirabe-Tetomu_a3ms_mgryhm.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623572452/wataridori/songs/cover/HibikiNoShirabe_bpze4m.jpg"},
  {name: "碧いうさぎ", author: "酒井法子",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623572579/wataridori/songs/AoiUsagiNgoiSaoMayManOST-NorikoSakai-79721_swkith.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623572575/wataridori/songs/cover/AoiUsagi_kzgdjl.jpg"},
  {name: "キセキ", author: "高橋李依",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623573820/wataridori/songs/Kiseki-RieTakahashi-6038192_aelbjy.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623573811/wataridori/songs/cover/kiseki_gyzoqc.jpg"},
  {name: "Orion", author: "MarieFD",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623574042/wataridori/songs/OrionAcousticArrange-MarieFD-5895479_xnj3hd.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623574038/wataridori/songs/cover/orion_vjbown.jpg"},
  {name: "君だったら", author: "Happy Birthday",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623574131/wataridori/songs/KimiDattara-HappyBirthday-3757129_vnqk55.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623574110/wataridori/songs/cover/kimi-dattara_tdvfen.jpg"},
  {name: "ひらり、ひらり", author: "初音ミク",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623574213/wataridori/songs/HazyMoon-HatsuneMiku-1689454_rabvzg.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623574210/wataridori/songs/cover/hazy-moon_jkx1wz.jpg"},
  {name: "雪の華", author: "中島美嘉",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1623574364/wataridori/songs/yuki-no-hana_fgt04c.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1623574352/wataridori/songs/cover/yuki-no-hana_nenl49.jpg"},
  {name: "Lá cờ", author: "Tạ Quang Thắng",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1634180057/wataridori/songs/la-co-ta-quang-thang_iuyrir.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1634180162/wataridori/songs/cover/la-co_jxfct5.jpg"},
  {name: "ハルウタ", author: "いきものがかり",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1631454241/wataridori/songs/haruuta_f9zjt2.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1631454200/wataridori/songs/cover/haruuta_oxrqvc.jpg"},
  {name: "YELL", author: "いきものがかり",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1631454530/wataridori/songs/yell_yxhpld.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1631454579/wataridori/songs/cover/yell_e1tn80.jpg"},
  {name: "ブルーバード", author: "いきものがかり",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1634181099/wataridori/songs/blue-bird_hz38c3.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1634181094/wataridori/songs/cover/blue-bird_okjecc.jpg"},
  {name: "Bài Ka Tuổi Trẻ", author: "Da LAB",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1635925086/wataridori/songs/bai-ca-tuoi-tre_aenx2m.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1635925156/wataridori/songs/cover/dalab_nmwibb.jpg"},
  {name: "Một Nhà", author: "Da LAB",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1636375488/wataridori/songs/mot-nha_t7lkdq.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1635925156/wataridori/songs/cover/dalab_nmwibb.jpg"},
  {name: "たぶん", author: "YOASOBI",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1636375305/wataridori/songs/tabun_hvzdsl.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1636375373/wataridori/songs/cover/tabun_jfpzr5.jpg"},
  {name: "Đưa nhau đi trốn", author: "Đen ft. Linh Cáo",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1636376600/wataridori/songs/dua-nhau-di-tron_e2oxol.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1636376399/wataridori/songs/cover/dua-nhau-di-tron_axos2a.jpg"},
  {name: "Đi về nhà", author: "Đen x JustaTee",
    url: "https://res.cloudinary.com/phucdx/video/upload/v1636376402/wataridori/songs/di-ve-nha_jhpjyr.mp3",
    cover: "https://res.cloudinary.com/phucdx/image/upload/v1636376401/wataridori/songs/cover/di-ve-nha_vjvnug.jpg"},
])
